import {
  checkImportDuplicates,
  commitImport,
  getTransactions,
  getTransactionYears,
  deleteTransaction,
  updateTransaction,
  splitTransaction,
  bulkUpdateTransactionsByIds,
  bulkUpdateTransactionsByFilter,
  bulkDeleteTransactionsByIds,
  bulkDeleteTransactionsByFilter,
  exportTransactionsCsv,
  searchTransactionsForReimbursement,
  getLinkedTransactions,
} from "@/app/actions/transactions";
import {
  getTrips,
  createTrip,
  getTrip,
  updateTrip,
  deleteTrip,
  getTripFundings,
  createTripFunding,
  reviewTripFundingMatch,
  mergeTripFunding,
  updateTripFunding,
  deleteTripFunding,
  getWallets,
  createWallet,
  recalculateWalletEntriesToBase,
  importTripSpendings,
  getFundingCandidates,
  getTripWalletSummaries,
  getTripEntries,
  searchTripEntriesForReimbursement,
  createTripReimbursementLink,
  clearTripEntryLinkage,
  getTripAnalytics,
  getSourceTransactionCandidates,
  addEntriesFromSourceTransactions,
  createTripEntry,
  getOutgoingFundingEntryCandidates,
  addFundingsFromOutgoingEntries,
  bulkUpdateTripEntriesByIds,
  bulkUpdateTripEntriesByFilter,
  bulkDeleteTripEntriesByIds,
  bulkDeleteTripEntriesByFilter,
} from "@/app/actions/trips";
import {
  getDashboardOverview,
  getDashboardReview,
  getImportSummaries,
  getImportDetail,
  getAnalyticsReport,
  getAnalyticsOverview,
  getAnalyticsInsights,
  getDashboardAnalytics,
  getMonthlyAnalytics,
} from "@/app/actions/analytics";
import {
  getCategories,
  createCategory,
  deleteCategory,
  updateCategory,
} from "@/app/actions/categories";
import {
  getAccountNumbers,
  upsertAccountNumber,
  updateAccountIdentifier,
  deleteAccountIdentifier,
} from "@/app/actions/accountNumbers";
import {
  bootstrapDefaultImportRules,
  getImportRules,
  createImportRule,
  updateImportRule,
  deleteImportRule,
  getPaylahInternalPreferenceState,
  setPaylahInternalPreference,
} from "@/app/actions/importRules";
import {
  getClassificationPatterns,
  rebuildClassificationPatterns,
  updateClassificationPattern,
  getAppliedClassificationSummary,
} from "@/app/actions/classificationPatterns";
import {
  getApiTokens,
  createApiToken,
  revokeApiToken,
  rotateApiToken,
} from "@/app/actions/apiTokens";
import {
  getAgentDrafts,
  getAgentDraft,
  getStagedReimbursementTargets,
  decideAgentProposal,
  updateAgentDraftRow,
  validateAgentDraft,
  commitAgentDraft,
} from "@/app/actions/agentDrafts";
import {
  getCurrentUser,
  updateUserProfile,
  updateAutoLabelSettings,
  updateAnalyticsExcludedCategories,
  changePassword,
} from "@/app/actions/user";
import { getAvailableParsers } from "@/app/actions/parser";

import { prepareReviewedTripRows } from "./tripImport";
async function commitReviewedTripImport(
  tripId: string,
  options: { walletId?: string; parserId?: string },
  rows: Record<string, any>[],
  selected: number[],
) {
  return importTripSpendings(
    tripId,
    options,
    prepareReviewedTripRows(rows, selected),
  );
}

// Explicit allowlist; new server actions are not exposed automatically.
export const mobileOperations = {
  commitReviewedTripImport,
  checkImportDuplicates,
  commitImport,
  getTransactions,
  getTransactionYears,
  deleteTransaction,
  updateTransaction,
  splitTransaction,
  bulkUpdateTransactionsByIds,
  bulkUpdateTransactionsByFilter,
  bulkDeleteTransactionsByIds,
  bulkDeleteTransactionsByFilter,
  exportTransactionsCsv,
  searchTransactionsForReimbursement,
  getLinkedTransactions,
  getTrips,
  createTrip,
  getTrip,
  updateTrip,
  deleteTrip,
  getTripFundings,
  createTripFunding,
  reviewTripFundingMatch,
  mergeTripFunding,
  updateTripFunding,
  deleteTripFunding,
  getWallets,
  createWallet,
  recalculateWalletEntriesToBase,
  importTripSpendings,
  getFundingCandidates,
  getTripWalletSummaries,
  getTripEntries,
  searchTripEntriesForReimbursement,
  createTripReimbursementLink,
  clearTripEntryLinkage,
  getTripAnalytics,
  getSourceTransactionCandidates,
  addEntriesFromSourceTransactions,
  createTripEntry,
  getOutgoingFundingEntryCandidates,
  addFundingsFromOutgoingEntries,
  bulkUpdateTripEntriesByIds,
  bulkUpdateTripEntriesByFilter,
  bulkDeleteTripEntriesByIds,
  bulkDeleteTripEntriesByFilter,
  getDashboardOverview,
  getDashboardReview,
  getImportSummaries,
  getImportDetail,
  getAnalyticsReport,
  getAnalyticsOverview,
  getAnalyticsInsights,
  getDashboardAnalytics,
  getMonthlyAnalytics,
  getCategories,
  createCategory,
  deleteCategory,
  updateCategory,
  getAccountNumbers,
  upsertAccountNumber,
  updateAccountIdentifier,
  deleteAccountIdentifier,
  bootstrapDefaultImportRules,
  getImportRules,
  createImportRule,
  updateImportRule,
  deleteImportRule,
  getPaylahInternalPreferenceState,
  setPaylahInternalPreference,
  getClassificationPatterns,
  rebuildClassificationPatterns,
  updateClassificationPattern,
  getAppliedClassificationSummary,
  getApiTokens,
  createApiToken,
  revokeApiToken,
  rotateApiToken,
  getAgentDrafts,
  getAgentDraft,
  getStagedReimbursementTargets,
  decideAgentProposal,
  updateAgentDraftRow,
  validateAgentDraft,
  commitAgentDraft,
  getCurrentUser,
  updateUserProfile,
  updateAutoLabelSettings,
  updateAnalyticsExcludedCategories,
  changePassword,
  getAvailableParsers,
};
